## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'internet', 'point-to-point', 'applications' ], mandatory = True)

def build(bld):
    bld.build_a_script('dce', needed = ['core', 'internet', 'dce', 'point-to-point', 'applications' ],
				  target='bin/dce-tcp-bulk-send',
				  source=['dce-tcp-bulk-send.cc'],
				  )

